// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBlacklistEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBlacklistEntry'](arg1, arg2, arg3);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetBlacklistEntries() {
  return window['go']['main']['App']['GetBlacklistEntries']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetMetricsDBStatus() {
  return window['go']['main']['App']['GetMetricsDBStatus']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function OpenCertFileDialog() {
  return window['go']['main']['App']['OpenCertFileDialog']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenKeyFileDialog() {
  return window['go']['main']['App']['OpenKeyFileDialog']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function QueryHistoricalMetrics(arg1) {
  return window['go']['main']['App']['QueryHistoricalMetrics'](arg1);
}

export function QueryRequestLogs(arg1) {
  return window['go']['main']['App']['QueryRequestLogs'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RefreshBlacklistCache() {
  return window['go']['main']['App']['RefreshBlacklistCache']();
}

export function RemoveBlacklistEntry(arg1) {
  return window['go']['main']['App']['RemoveBlacklistEntry'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function TestMetricsDBConnection(arg1) {
  return window['go']['main']['App']['TestMetricsDBConnection'](arg1);
}

export function UpdateRoute(arg1) {
  return window['go']['main']['App']['UpdateRoute'](arg1);
}
