// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBlacklistEntry(arg1:string,arg2:string,arg3:number):Promise<main.BlacklistEntry>;

export function CheckUpdate():Promise<main.CheckResult>;

export function ClearLogs():Promise<void>;

export function GetBlacklistEntries():Promise<Array<main.BlacklistEntry>>;

export function GetConfig():Promise<main.Config>;

export function GetLogs():Promise<Array<string>>;

export function GetMetrics():Promise<main.MetricsPayload>;

export function GetMetricsDBStatus():Promise<main.MetricsDBStatus>;

export function GetStatus():Promise<string>;

export function GetVersion():Promise<string>;

export function HideToTray():Promise<void>;

export function OpenCertFileDialog():Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenKeyFileDialog():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function QueryHistoricalMetrics(arg1:main.QueryMetricsRequest):Promise<main.QueryMetricsResponse>;

export function QueryRequestLogs(arg1:main.QueryRequestLogsRequest):Promise<main.QueryRequestLogsResponse>;

export function QuitApp():Promise<void>;

export function RefreshBlacklistCache():Promise<void>;

export function RemoveBlacklistEntry(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function TestMetricsDBConnection(arg1:string):Promise<boolean|string>;

export function UpdateRoute(arg1:main.Route):Promise<void>;
